### ISSUE TITLE
problem while launching Plugin

### ISSUE THREAD

**Issue by Selimooz** [MOCAP4ROS2-Project/mocap4ros2_gazebo#10]
I followed the steps from [this guide](https://mocap4ros2-project.github.io/getting_started/index.html). However, I'm encountering an error while spawning the project. I have already checked the paths inside the URDF file, but I still get the same error. How can I fix this issue?
![Screenshot from 2024-10-18 18-17-33](https://github.com/user-attachments/assets/ba0d0f87-0d8a-4632-b3c7-95111cce8ede)

**Comment by Juancams** [comment]
Hi!

The image you attached does not show any errors. Please tell us more about what is happening, detailing which version of Ubuntu and ROS 2 you are using.

The steps in the guide are not up to date, although I see that the launcher you are running is the correct one. Please also check that before launching it you are doing this:
```bash
export TURTLEBOT3_MODEL=waffle
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/home/<your-user>/mocap4r2_ws/install/gazebo_mocap4r2_plugin/share/gazebo_mocap4r2_plugin/models/
source /usr/share/gazebo/setup.bash
```

Remember to change <your-user> to your user, verifying that the path you enter is correct.

We look forward to your response.

Greetings.

**Comment by Selimooz** [comment]
Thank you for your response. I am using ROS2 Humble on Ubuntu 22.04. The issue I am encountering occurs after spawning. Normally, I get a successful spawn_entity, but as you can see, the last message I receive is: "Waiting for service /spawn_entity", followed by a timeout error: "Timed out waiting for transform from base_link to map." I have also used the commands, and the path I provided is correct. I still get the same msgs.
![Screenshot from 2024-10-19 12-37-11](https://github.com/user-attachments/assets/7729614c-7136-446d-bcf6-08dbf89d81f6)

![Screenshot from 2024-10-19 12-37-19](https://github.com/user-attachments/assets/caa4a2f1-d004-4a4c-a5ee-1e89a600fb2c)

**Comment by Juancams** [comment]
Perfect. Did you try the lines I mentioned? Also, once you have launched everything, you have to locate the robot inside the world.

Please try what I mentioned and tell me if it worked for you. You can also see if the bot has spawned correctly by running `gzclient` from another terminal.

**Comment by Selimooz** [comment]
I did it. How can I locate the robot inside the world in the waffle.model? I haven’t changed anything. When I try to open Gazebo, I don’t see anything, as shown in the screenshot.

![Screenshot from 2024-10-19 17-59-33](https://github.com/user-attachments/assets/f45ad7ff-5571-413d-a0eb-05ebb31ad9dc)

**Comment by Juancams** [comment]
I have checked inside a docker and everything works correctly, so it has to be an error that you are just having.

I would tell you to enter this inside your bashrc, close all the terminals and follow the steps again.
```bash
export TURTLEBOT3_MODEL=waffle
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/home/<your-user>/mocap4r2_ws/install/gazebo_mocap4r2_plugin/share/gazebo_mocap4r2_plugin/models/
source /usr/share/gazebo/setup.bash
```

Remember to change to your user, verifying that the path you enter is correct.

**Comment by Selimooz** [comment]
Thanks. It is working now. The problem was with the directory paths inside the URDF and waffle.model files.

**Comment by Selimooz** [comment]
I have another question: Can I use Gazebo with Optitrack? 
Also, is it possible to make Rviz display my drone? Currently, I only see points in Rviz, but I want to make my drone model appear."

**Comment by Juancams** [comment]
To do that, you'll need to add your RobotModel to the rviz visualization, as I show on the screenshot.

![image](https://github.com/user-attachments/assets/df344c36-e28f-4562-a58a-f95d532a17ec)

You'll also need to be publishing your urdf to the `/robot_description` topic, and putting it in the rviz RobotModel.
