### ISSUE TITLE
rename main to rolling

### ISSUE THREAD

**Issue by fmrico** [MOCAP4ROS2-Project/mocap4ros2_gazebo#12]
Hi @Juancams 

What do you think about renaming the `main` branch to `rolling`, and start pointing to this distro for active development?

Best

**Comment by Juancams** [comment]
Sounds good to me, right now we have changed the main to humble-devel because it only works in classic gazebo

We can start from this to make the rolling branch in the new gazebo.

**Comment by jmguerreroh** [comment]
Done, now rolling is the default branch
